"""empty message

Revision ID: 14f93867441d
Revises: 1c87535cb97f
Create Date: 2024-02-05 16:00:19.205881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14f93867441d'
down_revision = '1c87535cb97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))
        batch_op.alter_column('duedate',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('duedate',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
