"""empty message

Revision ID: 1c87535cb97f
Revises: 60f313e2e81b
Create Date: 2024-02-05 15:38:30.658637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c87535cb97f'
down_revision = '60f313e2e81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duedate', sa.String(length=100), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('duedate')
        batch_op.drop_column('description')
        batch_op.drop_column('task')

    # ### end Alembic commands ###
